name: Test React Library
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Fix dependencies
        run: |
          rm -rf /node_modules/string-width|
          cp /node_modules/string-width-cjs /node_modules/string-width|
          rm -rf /node_modules/string-width-cjs|
      - name: Test library
        run: yarn run test
